import type { NextPage } from "next";
import Head from "next/head";

import { FirstSection, SecondSection, ThirdSection } from "../components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Boda Pérez Flores 👰🏻‍♀️🤵🏻‍♂️❤️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FirstSection />
        <SecondSection />
        <ThirdSection />
      </main>
    </>
  );
};

export default Home;
