import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="parallax w-screen h-screen">
          {" "}
          <h1>Helllo</h1>
        </div>

        <div className="w-full">
          Scroll Up and Down this page to see the parallax scrolling effect.
          This div is just here to enable scrolling. Tip: Try to remove the
          background-attachment property to remove the scrolling effect.
        </div>
        <br />
        <div className="w-full">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo
          natus obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam! Lorem ipsum dolor, sit amet consectetur adipisicing
          elit. Maiores nemo natus obcaecati libero laudantium fuga vitae error
          praesentium optio accusamus sit, ipsa soluta eligendi! Sunt vitae
          nesciunt temporibus quaerat veniam! Lorem ipsum dolor, sit amet
          consectetur adipisicing elit. Maiores nemo natus obcaecati libero
          laudantium fuga vitae error praesentium optio accusamus sit, ipsa
          soluta eligendi! Sunt vitae nesciunt temporibus quaerat veniam! Lorem
          ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo natus
          obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam! Lorem ipsum dolor, sit amet consectetur adipisicing
          elit. Maiores nemo natus obcaecati libero laudantium fuga vitae error
          praesentium optio accusamus sit, ipsa soluta eligendi! Sunt vitae
          nesciunt temporibus quaerat veniam! Lorem ipsum dolor, sit amet
          consectetur adipisicing elit. Maiores nemo natus obcaecati libero
          laudantium fuga vitae error praesentium optio accusamus sit, ipsa
          soluta eligendi! Sunt vitae nesciunt temporibus quaerat veniam! Lorem
          ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo natus
          obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam! Lorem ipsum dolor, sit amet consectetur adipisicing
          elit. Maiores nemo natus obcaecati libero laudantium fuga vitae error
          praesentium optio accusamus sit, ipsa soluta eligendi! Sunt vitae
          nesciunt temporibus quaerat veniam! Lorem ipsum dolor, sit amet
          consectetur adipisicing elit. Maiores nemo natus obcaecati libero
          laudantium fuga vitae error praesentium optio accusamus sit, ipsa
          soluta eligendi! Sunt vitae nesciunt temporibus quaerat veniam! Lorem
          ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo natus
          obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam! v
        </div>
        <br />
        <div className="w-full">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo
          natus obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam!
        </div>
        <br />
        <div className="w-full">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo
          natus obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam!
        </div>
        <br />
        <div className="w-full">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores nemo
          natus obcaecati libero laudantium fuga vitae error praesentium optio
          accusamus sit, ipsa soluta eligendi! Sunt vitae nesciunt temporibus
          quaerat veniam!
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
